name: mir-kiosk
adopt-info: mir-kiosk
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
base: core20
license: GPL-3.0 OR GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
#  - build-on: i386

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  # Prep EGL
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

layout:
  /usr/share:
    bind: $SNAP/usr/share

apps:
  mir-kiosk:
    command: bin/run-user $SNAP/bin/run-miral
    plugs:
      - login-session-control
      - x11

  daemon:
    command: bin/run-daemon $SNAP/bin/run-miral
    daemon: simple
    restart-delay: 3s
    environment:
      # XDG config
      XDG_CONFIG_HOME: $SNAP_DATA
      HOME: $SNAP_DATA

slots:
  wayland:

plugs:
  opengl:

parts:
  mir:
    plugin: nil
    stage-snaps:
    - mir-core20
    stage:
    - -*.h
    - -*.pc
    - -share

  mir-kiosk:
    after: [mir]
    plugin: nil
    source: .
    source-type: git
    override-pull: |
      snapcraftctl pull
      recipe_version=$( git rev-list --count HEAD )
      mir_version=$( sed -rne 's/^version:\s+([^-]*)-.+$/\1/p' ${SNAPCRAFT_STAGE}/meta.mir-core20/snap.yaml )
      snapcraftctl set-version $mir_version-snap$recipe_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    stage-packages:
    - libgl1-mesa-dri

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    prime:
      - -usr/share/doc

  glue:
    plugin: dump
    source: glue
