name: mir-kiosk
adopt-info: mir-demos
summary: A minimal Mir based shell for kiosk type applications
description: A minimal Mir based shell for kiosk type applications
confinement: strict
base: core20
license: GPL-3.0 OR GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
#  - build-on: i386

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  # Prep EGL
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

layout:
  /usr/share:
    bind: $SNAP/usr/share

apps:
  mir-kiosk:
    command: bin/run-user $SNAP/bin/run-miral
    plugs:
      - login-session-control
      - x11

  daemon:
    command: bin/run-daemon $SNAP/bin/run-miral
    daemon: simple
    restart-delay: 3s
    environment:
      # XDG config
      XDG_CONFIG_HOME: $SNAP_DATA
      HOME: $SNAP_DATA

slots:
  wayland:

plugs:
  opengl:

package-repositories:
- type: apt
  ppa: mir-team/release

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  mir-demos:
    after: [recipe-version]
    plugin: nil
    stage-packages:
      - mir-demos
      - mir-platform-graphics-gbm-kms
      - mir-platform-graphics-x
      - libgl1-mesa-dri
    override-build: |
      mir_version=`LANG=C apt-cache policy mir-demos | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $mir_version-snap$recipe_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
      snapcraftctl build
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
      - -usr/share/wayland-sessions
      - -usr/bin/fake-mir-kiosk
      - -usr/bin/miral-app
      - -usr/bin/miral-desktop
      - -usr/bin/miral-run
      - -usr/bin/miral-shell
      - -usr/bin/miral-system-compositor
      - -usr/bin/miral-terminal
      - -usr/bin/mir-shell
      # mir-demos pulls in inotify-tools, but we don't use it
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libinotifytools.so.0.*
      - -usr/bin/inotify*

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    prime:
      - -usr/share/doc

  glue:
    plugin: dump
    source: glue
