#!/bin/sh
set -e

# If 'vt.handoff' is set, Mir only starts first time on the default VT. (#779)
# Until we understand and fix properly, set the config the way that works.
vt=$(sed -n 's/.*vt.handoff=\([^ ]*\).*/\1/p' /proc/cmdline)
if [ -z "$vt" ]
then vt=4
else vt=0
fi

snapctl set display-layout=default vt=$vt cursor=auto
